### ISSUE TITLE
Add Strategy to Ueberauth strategy list

### ISSUE THREAD

**Issue by doomspork** [sdn90/ueberauth_shopify#1]
Hi @sdn90, thank you for taking the initiative to create this strategy!  We'd love to include your package on [Ueberauth's List of Strategies](https://github.com/ueberauth/ueberauth/wiki/List-of-Strategies), would you be open to adding it?

**Comment by sdn90** [comment]
Hey @doomspork, sounds great. Will send a PR once I have the documentation ready.
